# Generated by Django 6.0.4 on 2026-05-03 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_purchases'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchases',
            new_name='Purchase',
        ),
    ]
